name: Python Package using Conda

on: [push]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: '3.10'
    - name: Add conda to system path
      run: |
        echo $CONDA/bin >> $GITHUB_PATH
    - name: Cache Conda packages
      uses: actions/cache@v3
      id: cache
      with:
        path: ~/.conda/pkgs
        key: ${{ runner.os }}-conda-${{ hashFiles('environment.yml') }}
        restore-keys: |
          ${{ runner.os }}-conda-
    - name: Install dependencies
      run: |
        conda env update --file environment.yml --name base --channel conda-forge
    - name: Lint with flake8
      run: |
        conda install flake8
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Test with pytest
      run: |
        conda install pytest
        pytest
    - name: Deploy to Railway.app
      uses: railwayapp/deploy@v1
      with:
        api-key: ${{ secrets.RAILWAY_API_KEY }}
        project-id: ${{ secrets.RAILWAY_PROJECT_ID }}
